//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.RESERVAS = new HashSet<RESERVAS>();
        }
    
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Perfil { get; set; }
        public Nullable<int> Borrado { get; set; }
    
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
    }
}
